version: '3.3'
services:
  web:
    build: .
    container_name: flask_web
    ports:
      - 5000:5000
    volumes:
      - .:/code
    depends_on:
      - redis
      - worker
  
  worker:
    build: .
    container_name: worker
    depends_on:
      - redis
    command: rq worker --url redis://redis:6379/0
  
  redis:
    image: "redis:alpine"